function SPIROPAchl = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SPIROPACHL = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  SPIROPACHL = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  SPIROPACHL = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  SPIROPAchl = importfile("\\sosiknas1\Lab_data\SPIROPA\CHL\SPIROPAchl.xlsx", "chl", [2, 3887]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Nov-2019 08:23:42

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 3887];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 28);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AB" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Cruise", "Cast", "Niskin", "TargetDepth", "Replicate", "VolFilt", "FilterSize", "VolExtracted", "Sample", "Acetone", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Rbblank", "Rablank", "Chlugl", "Phaeougl", "Cal_Date", "Fluorometer", "Labnotebookandpagenumber", "Comments", "quality_flag", "Sample1", "Acetone1"];
opts.SelectedVariableNames = ["Cruise", "Cast", "Niskin", "TargetDepth", "Replicate", "VolFilt", "FilterSize", "VolExtracted", "Sample", "Acetone", "DilutionDuringReading", "Chl_Cal_Filename", "tau_Calibration", "Fd_Calibration", "Rb", "Ra", "blank", "Rbblank", "Rablank", "Chlugl", "Phaeougl", "Cal_Date", "Fluorometer", "Labnotebookandpagenumber", "Comments", "quality_flag", "Sample1", "Acetone1"];
opts.VariableTypes = ["categorical", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime", "string", "categorical", "categorical", "double", "double", "double"];
opts = setvaropts(opts, 22, "InputFormat", "");
opts = setvaropts(opts, 23, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 5, 12, 23, 24, 25], "EmptyFieldRule", "auto");

% Import the data
SPIROPAchl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AB" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    SPIROPAchl = [SPIROPAchl; tb]; %#ok<AGROW>
end

end